/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    posts: Post;
    projects: Project;
    media: Media;
    categories: Category;
    users: User;
    redirects: Redirect;
    forms: Form;
    'form-submissions': FormSubmission;
    search: Search;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'media';
    };
  };
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  hero: {
    type: 'none' | 'highImpact' | 'mediumImpact' | 'lowImpact' | 'blob' | 'shader';
    richText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    links?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: number | Page;
                } | null)
              | ({
                  relationTo: 'posts';
                  value: number | Post;
                } | null);
            url?: string | null;
            label: string;
            /**
             * Choose how the link should be rendered.
             */
            appearance?: ('default' | 'outline') | null;
          };
          id?: string | null;
        }[]
      | null;
    media?: (number | null) | Media;
    shaderType?:
      | (
          | 'meshGradient'
          | 'smokeRing'
          | 'neuroNoise'
          | 'dotOrbit'
          | 'dotGrid'
          | 'simplexNoise'
          | 'metaballs'
          | 'waves'
          | 'perlinNoise'
          | 'voronoi'
          | 'warp'
          | 'godRays'
          | 'spiral'
          | 'swirl'
          | 'dithering'
          | 'grainGradient'
          | 'pulsingBorder'
          | 'colorPanels'
          | 'staticMeshGradient'
          | 'staticRadialGradient'
          | 'paperTexture'
          | 'flutedGlass'
          | 'water'
          | 'imageDithering'
          | 'heatmap'
          | 'liquidMetal'
          | 'halftoneDots'
          | 'halftoneCmyk'
        )
      | null;
    /**
     * Negative values reverse the animation. 0 = static.
     */
    shaderSpeed?: number | null;
    shaderScale?: number | null;
    shaderRotation?: number | null;
    meshGradientColors?:
      | {
          /**
           * CSS color value
           */
          color: string;
          id?: string | null;
        }[]
      | null;
    meshGradientDistortion?: number | null;
    meshGradientSwirl?: number | null;
    meshGradientGrainMixer?: number | null;
    meshGradientGrainOverlay?: number | null;
    smokeRingColors?:
      | {
          /**
           * CSS color value
           */
          color: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Any CSS color value (e.g. #ff0000, rgba(255,0,0,1))
     */
    smokeRingColorBack?: string | null;
    smokeRingThickness?: number | null;
    smokeRingRadius?: number | null;
    smokeRingInnerShape?: number | null;
    smokeRingNoiseIterations?: number | null;
    smokeRingNoiseScale?: number | null;
    /**
     * Any CSS color value (e.g. #ff0000, rgba(255,0,0,1))
     */
    neuroNoiseColorFront?: string | null;
    /**
     * Any CSS color value (e.g. #ff0000, rgba(255,0,0,1))
     */
    neuroNoiseColorMid?: string | null;
    /**
     * Any CSS color value (e.g. #ff0000, rgba(255,0,0,1))
     */
    neuroNoiseColorBack?: string | null;
    neuroNoiseBrightness?: number | null;
    neuroNoiseContrast?: number | null;
    dotOrbitColors?:
      | {
          /**
           * CSS color value
           */
          color: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Any CSS color value (e.g. #ff0000, rgba(255,0,0,1))
     */
    dotOrbitColorBack?: string | null;
    dotOrbitSize?: number | null;
    dotOrbitSizeRange?: number | null;
    dotOrbitSpreading?: number | null;
    dotOrbitStepsPerColor?: number | null;
    /**
     * Any CSS color value (e.g. #ff0000, rgba(255,0,0,1))
     */
    dotGridColorBack?: string | null;
    /**
     * Any CSS color value (e.g. #ff0000, rgba(255,0,0,1))
     */
    dotGridColorFill?: string | null;
    /**
     * Any CSS color value (e.g. #ff0000, rgba(255,0,0,1))
     */
    dotGridColorStroke?: string | null;
    dotGridSize?: number | null;
    dotGridGapX?: number | null;
    dotGridGapY?: number | null;
    dotGridStrokeWidth?: number | null;
    dotGridSizeRange?: number | null;
    dotGridOpacityRange?: number | null;
    dotGridShape?: ('circle' | 'diamond' | 'square' | 'triangle') | null;
    simplexNoiseColors?:
      | {
          /**
           * CSS color value
           */
          color: string;
          id?: string | null;
        }[]
      | null;
    simplexNoiseStepsPerColor?: number | null;
    simplexNoiseSoftness?: number | null;
    metaballsColors?:
      | {
          /**
           * CSS color value
           */
          color: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Any CSS color value (e.g. #ff0000, rgba(255,0,0,1))
     */
    metaballsColorBack?: string | null;
    metaballsCount?: number | null;
    metaballsSize?: number | null;
    /**
     * Any CSS color value (e.g. #ff0000, rgba(255,0,0,1))
     */
    wavesColorFront?: string | null;
    /**
     * Any CSS color value (e.g. #ff0000, rgba(255,0,0,1))
     */
    wavesColorBack?: string | null;
    wavesShape?: number | null;
    wavesAmplitude?: number | null;
    wavesFrequency?: number | null;
    wavesSpacing?: number | null;
    wavesProportion?: number | null;
    wavesSoftness?: number | null;
    /**
     * Any CSS color value (e.g. #ff0000, rgba(255,0,0,1))
     */
    perlinNoiseColorFront?: string | null;
    /**
     * Any CSS color value (e.g. #ff0000, rgba(255,0,0,1))
     */
    perlinNoiseColorBack?: string | null;
    perlinNoiseProportion?: number | null;
    perlinNoiseSoftness?: number | null;
    perlinNoiseOctaveCount?: number | null;
    perlinNoisePersistence?: number | null;
    perlinNoiseLacunarity?: number | null;
    voronoiColors?:
      | {
          /**
           * CSS color value
           */
          color: string;
          id?: string | null;
        }[]
      | null;
    voronoiStepsPerColor?: number | null;
    /**
     * Any CSS color value (e.g. #ff0000, rgba(255,0,0,1))
     */
    voronoiColorGap?: string | null;
    /**
     * Any CSS color value (e.g. #ff0000, rgba(255,0,0,1))
     */
    voronoiColorGlow?: string | null;
    voronoiDistortion?: number | null;
    voronoiGap?: number | null;
    voronoiGlow?: number | null;
    warpColors?:
      | {
          /**
           * CSS color value
           */
          color: string;
          id?: string | null;
        }[]
      | null;
    warpProportion?: number | null;
    warpSoftness?: number | null;
    warpShape?: ('checks' | 'stripes' | 'edge') | null;
    warpShapeScale?: number | null;
    warpDistortion?: number | null;
    warpSwirl?: number | null;
    warpSwirlIterations?: number | null;
    godRaysColors?:
      | {
          /**
           * CSS color value
           */
          color: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Any CSS color value (e.g. #ff0000, rgba(255,0,0,1))
     */
    godRaysColorBack?: string | null;
    /**
     * Any CSS color value (e.g. #ff0000, rgba(255,0,0,1))
     */
    godRaysColorBloom?: string | null;
    godRaysBloom?: number | null;
    godRaysIntensity?: number | null;
    godRaysDensity?: number | null;
    godRaysSpotty?: number | null;
    godRaysMidSize?: number | null;
    godRaysMidIntensity?: number | null;
    /**
     * Any CSS color value (e.g. #ff0000, rgba(255,0,0,1))
     */
    spiralColorFront?: string | null;
    /**
     * Any CSS color value (e.g. #ff0000, rgba(255,0,0,1))
     */
    spiralColorBack?: string | null;
    spiralDensity?: number | null;
    spiralDistortion?: number | null;
    spiralStrokeWidth?: number | null;
    spiralStrokeTaper?: number | null;
    spiralStrokeCap?: number | null;
    spiralNoise?: number | null;
    spiralNoiseFrequency?: number | null;
    spiralSoftness?: number | null;
    swirlColors?:
      | {
          /**
           * CSS color value
           */
          color: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Any CSS color value (e.g. #ff0000, rgba(255,0,0,1))
     */
    swirlColorBack?: string | null;
    swirlBandCount?: number | null;
    swirlTwist?: number | null;
    swirlCenter?: number | null;
    swirlProportion?: number | null;
    swirlSoftness?: number | null;
    swirlNoise?: number | null;
    swirlNoiseFrequency?: number | null;
    /**
     * Any CSS color value (e.g. #ff0000, rgba(255,0,0,1))
     */
    ditheringColorFront?: string | null;
    /**
     * Any CSS color value (e.g. #ff0000, rgba(255,0,0,1))
     */
    ditheringColorBack?: string | null;
    ditheringShape?: ('simplex' | 'warp' | 'dots' | 'wave' | 'ripple' | 'swirl' | 'sphere') | null;
    ditheringType?: ('random' | '2x2' | '4x4' | '8x8') | null;
    ditheringSize?: number | null;
    grainGradientColors?:
      | {
          /**
           * CSS color value
           */
          color: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Any CSS color value (e.g. #ff0000, rgba(255,0,0,1))
     */
    grainGradientColorBack?: string | null;
    grainGradientSoftness?: number | null;
    grainGradientIntensity?: number | null;
    grainGradientNoise?: number | null;
    grainGradientShape?: ('wave' | 'dots' | 'truchet' | 'corners' | 'ripple' | 'blob' | 'sphere') | null;
    pulsingBorderColors?:
      | {
          /**
           * CSS color value
           */
          color: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Any CSS color value (e.g. #ff0000, rgba(255,0,0,1))
     */
    pulsingBorderColorBack?: string | null;
    pulsingBorderRoundness?: number | null;
    pulsingBorderThickness?: number | null;
    pulsingBorderSoftness?: number | null;
    pulsingBorderMargin?: number | null;
    pulsingBorderMarginLeft?: number | null;
    pulsingBorderMarginRight?: number | null;
    pulsingBorderMarginTop?: number | null;
    pulsingBorderMarginBottom?: number | null;
    pulsingBorderAspectRatio?: ('auto' | 'square') | null;
    pulsingBorderIntensity?: number | null;
    pulsingBorderBloom?: number | null;
    pulsingBorderSpots?: number | null;
    pulsingBorderSpotSize?: number | null;
    pulsingBorderPulse?: number | null;
    pulsingBorderSmoke?: number | null;
    pulsingBorderSmokeSize?: number | null;
    colorPanelsColors?:
      | {
          /**
           * CSS color value
           */
          color: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Any CSS color value (e.g. #ff0000, rgba(255,0,0,1))
     */
    colorPanelsColorBack?: string | null;
    colorPanelsAngle1?: number | null;
    colorPanelsAngle2?: number | null;
    colorPanelsLength?: number | null;
    colorPanelsEdges?: boolean | null;
    colorPanelsBlur?: number | null;
    colorPanelsFadeIn?: number | null;
    colorPanelsFadeOut?: number | null;
    colorPanelsDensity?: number | null;
    colorPanelsGradient?: number | null;
    staticMeshGradientColors?:
      | {
          /**
           * CSS color value
           */
          color: string;
          id?: string | null;
        }[]
      | null;
    staticMeshGradientPositions?: number | null;
    staticMeshGradientWaveX?: number | null;
    staticMeshGradientWaveXShift?: number | null;
    staticMeshGradientWaveY?: number | null;
    staticMeshGradientWaveYShift?: number | null;
    staticMeshGradientMixing?: number | null;
    staticMeshGradientGrainMixer?: number | null;
    staticMeshGradientGrainOverlay?: number | null;
    staticRadialGradientColors?:
      | {
          /**
           * CSS color value
           */
          color: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Any CSS color value (e.g. #ff0000, rgba(255,0,0,1))
     */
    staticRadialGradientColorBack?: string | null;
    staticRadialGradientRadius?: number | null;
    staticRadialGradientFocalDistance?: number | null;
    staticRadialGradientFocalAngle?: number | null;
    staticRadialGradientFalloff?: number | null;
    staticRadialGradientMixing?: number | null;
    staticRadialGradientDistortion?: number | null;
    staticRadialGradientDistortionShift?: number | null;
    staticRadialGradientDistortionFreq?: number | null;
    staticRadialGradientGrainMixer?: number | null;
    staticRadialGradientGrainOverlay?: number | null;
    /**
     * Any CSS color value (e.g. #ff0000, rgba(255,0,0,1))
     */
    paperTextureColorFront?: string | null;
    /**
     * Any CSS color value (e.g. #ff0000, rgba(255,0,0,1))
     */
    paperTextureColorBack?: string | null;
    paperTextureContrast?: number | null;
    paperTextureRoughness?: number | null;
    paperTextureFiber?: number | null;
    paperTextureFiberSize?: number | null;
    paperTextureCrumples?: number | null;
    paperTextureCrumpleSize?: number | null;
    paperTextureFolds?: number | null;
    paperTextureFoldCount?: number | null;
    paperTextureFade?: number | null;
    paperTextureDrops?: number | null;
    paperTextureSeed?: number | null;
    /**
     * Any CSS color value (e.g. #ff0000, rgba(255,0,0,1))
     */
    flutedGlassColorBack?: string | null;
    /**
     * Any CSS color value (e.g. #ff0000, rgba(255,0,0,1))
     */
    flutedGlassColorShadow?: string | null;
    /**
     * Any CSS color value (e.g. #ff0000, rgba(255,0,0,1))
     */
    flutedGlassColorHighlight?: string | null;
    flutedGlassShadows?: number | null;
    flutedGlassHighlights?: number | null;
    flutedGlassSize?: number | null;
    flutedGlassShape?: ('lines' | 'linesIrregular' | 'wave' | 'zigzag' | 'pattern') | null;
    flutedGlassAngle?: number | null;
    flutedGlassDistortionShape?: ('prism' | 'lens' | 'contour' | 'cascade' | 'flat') | null;
    flutedGlassDistortion?: number | null;
    flutedGlassShift?: number | null;
    flutedGlassStretch?: number | null;
    flutedGlassBlur?: number | null;
    flutedGlassEdges?: number | null;
    flutedGlassMargin?: number | null;
    flutedGlassGrainMixer?: number | null;
    flutedGlassGrainOverlay?: number | null;
    /**
     * Any CSS color value (e.g. #ff0000, rgba(255,0,0,1))
     */
    waterColorBack?: string | null;
    /**
     * Any CSS color value (e.g. #ff0000, rgba(255,0,0,1))
     */
    waterColorHighlight?: string | null;
    waterHighlights?: number | null;
    waterLayering?: number | null;
    waterEdges?: number | null;
    waterCaustic?: number | null;
    waterWaves?: number | null;
    waterSize?: number | null;
    /**
     * Any CSS color value (e.g. #ff0000, rgba(255,0,0,1))
     */
    imageDitheringColorFront?: string | null;
    /**
     * Any CSS color value (e.g. #ff0000, rgba(255,0,0,1))
     */
    imageDitheringColorBack?: string | null;
    /**
     * Any CSS color value (e.g. #ff0000, rgba(255,0,0,1))
     */
    imageDitheringColorHighlight?: string | null;
    imageDitheringType?: ('random' | '2x2' | '4x4' | '8x8') | null;
    imageDitheringSize?: number | null;
    imageDitheringColorSteps?: number | null;
    imageDitheringOriginalColors?: boolean | null;
    imageDitheringInverted?: boolean | null;
    heatmapColors?:
      | {
          /**
           * CSS color value
           */
          color: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Any CSS color value (e.g. #ff0000, rgba(255,0,0,1))
     */
    heatmapColorBack?: string | null;
    heatmapContour?: number | null;
    heatmapAngle?: number | null;
    heatmapNoise?: number | null;
    heatmapInnerGlow?: number | null;
    heatmapOuterGlow?: number | null;
    /**
     * Any CSS color value (e.g. #ff0000, rgba(255,0,0,1))
     */
    liquidMetalColorBack?: string | null;
    /**
     * Any CSS color value (e.g. #ff0000, rgba(255,0,0,1))
     */
    liquidMetalColorTint?: string | null;
    liquidMetalRepetition?: number | null;
    liquidMetalSoftness?: number | null;
    liquidMetalShiftRed?: number | null;
    liquidMetalShiftBlue?: number | null;
    liquidMetalDistortion?: number | null;
    liquidMetalContour?: number | null;
    liquidMetalAngle?: number | null;
    liquidMetalShape?: ('none' | 'circle' | 'daisy' | 'diamond' | 'metaballs') | null;
    /**
     * Any CSS color value (e.g. #ff0000, rgba(255,0,0,1))
     */
    halftoneDotsColorFront?: string | null;
    /**
     * Any CSS color value (e.g. #ff0000, rgba(255,0,0,1))
     */
    halftoneDotsColorBack?: string | null;
    halftoneDotsSize?: number | null;
    halftoneDotsGrid?: ('square' | 'hex') | null;
    halftoneDotsRadius?: number | null;
    halftoneDotsContrast?: number | null;
    halftoneDotsOriginalColors?: boolean | null;
    halftoneDotsInverted?: boolean | null;
    halftoneDotsGrainMixer?: number | null;
    halftoneDotsGrainOverlay?: number | null;
    halftoneDotsGrainSize?: number | null;
    halftoneDotsType?: ('classic' | 'gooey' | 'holes' | 'soft') | null;
    /**
     * Any CSS color value (e.g. #ff0000, rgba(255,0,0,1))
     */
    halftoneCmykColorBack?: string | null;
    /**
     * Any CSS color value (e.g. #ff0000, rgba(255,0,0,1))
     */
    halftoneCmykColorC?: string | null;
    /**
     * Any CSS color value (e.g. #ff0000, rgba(255,0,0,1))
     */
    halftoneCmykColorM?: string | null;
    /**
     * Any CSS color value (e.g. #ff0000, rgba(255,0,0,1))
     */
    halftoneCmykColorY?: string | null;
    /**
     * Any CSS color value (e.g. #ff0000, rgba(255,0,0,1))
     */
    halftoneCmykColorK?: string | null;
    halftoneCmykSize?: number | null;
    halftoneCmykMinDot?: number | null;
    halftoneCmykContrast?: number | null;
    halftoneCmykSoftness?: number | null;
    halftoneCmykGrainSize?: number | null;
    halftoneCmykGrainMixer?: number | null;
    halftoneCmykGrainOverlay?: number | null;
    halftoneCmykGridNoise?: number | null;
    halftoneCmykFloodC?: number | null;
    halftoneCmykFloodM?: number | null;
    halftoneCmykFloodY?: number | null;
    halftoneCmykFloodK?: number | null;
    halftoneCmykGainC?: number | null;
    halftoneCmykGainM?: number | null;
    halftoneCmykGainY?: number | null;
    halftoneCmykGainK?: number | null;
    halftoneCmykType?: ('dots' | 'ink' | 'sharp') | null;
  };
  layout: (CallToActionBlock | ContentBlock | MediaBlock | ArchiveBlock | FormBlock | OurProcessBlock)[];
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  heroImage?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  relatedPosts?: (number | Post)[] | null;
  categories?: (number | Category)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  authors?: (number | User)[] | null;
  populatedAuthors?:
    | {
        id?: string | null;
        name?: string | null;
      }[]
    | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  folder?: (number | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: number;
  name: string;
  folder?: (number | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: number | FolderInterface;
        }
      | {
          relationTo?: 'media';
          value: number | Media;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: 'media'[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  parent?: (number | null) | Category;
  breadcrumbs?:
    | {
        doc?: (number | null) | Category;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  richText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  columns?:
    | {
        size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
        richText?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        enableLink?: boolean | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: number | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock".
 */
export interface ArchiveBlock {
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  populateBy?: ('collection' | 'selection') | null;
  relationTo?: ('posts' | 'projects') | null;
  categories?: (number | Category)[] | null;
  limit?: number | null;
  selectedDocs?:
    | (
        | {
            relationTo: 'posts';
            value: number | Post;
          }
        | {
            relationTo: 'projects';
            value: number | Project;
          }
      )[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'archive';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  featuredImage: number | Media;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  client?: string | null;
  date?: string | null;
  location?: string | null;
  projectStatus?: ('inProgress' | 'completed' | 'speculative' | 'competition') | null;
  description?: string | null;
  categories?: (number | Category)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock".
 */
export interface FormBlock {
  form: number | Form;
  enableIntro?: boolean | null;
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "OurProcessBlock".
 */
export interface OurProcessBlock {
  heading?: string | null;
  subHeading?: string | null;
  steps: {
    title: string;
    description?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    image: number | Media;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'ourProcess';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * You will need to rebuild the website when changing this field.
   */
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: number;
  title?: string | null;
  priority?: number | null;
  doc: {
    relationTo: 'posts';
    value: number | Post;
  };
  slug?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  categories?:
    | {
        relationTo?: string | null;
        categoryID?: string | null;
        title?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'search';
        value: number | Search;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: number | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  hero?:
    | T
    | {
        type?: T;
        richText?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                    appearance?: T;
                  };
              id?: T;
            };
        media?: T;
        shaderType?: T;
        shaderSpeed?: T;
        shaderScale?: T;
        shaderRotation?: T;
        meshGradientColors?:
          | T
          | {
              color?: T;
              id?: T;
            };
        meshGradientDistortion?: T;
        meshGradientSwirl?: T;
        meshGradientGrainMixer?: T;
        meshGradientGrainOverlay?: T;
        smokeRingColors?:
          | T
          | {
              color?: T;
              id?: T;
            };
        smokeRingColorBack?: T;
        smokeRingThickness?: T;
        smokeRingRadius?: T;
        smokeRingInnerShape?: T;
        smokeRingNoiseIterations?: T;
        smokeRingNoiseScale?: T;
        neuroNoiseColorFront?: T;
        neuroNoiseColorMid?: T;
        neuroNoiseColorBack?: T;
        neuroNoiseBrightness?: T;
        neuroNoiseContrast?: T;
        dotOrbitColors?:
          | T
          | {
              color?: T;
              id?: T;
            };
        dotOrbitColorBack?: T;
        dotOrbitSize?: T;
        dotOrbitSizeRange?: T;
        dotOrbitSpreading?: T;
        dotOrbitStepsPerColor?: T;
        dotGridColorBack?: T;
        dotGridColorFill?: T;
        dotGridColorStroke?: T;
        dotGridSize?: T;
        dotGridGapX?: T;
        dotGridGapY?: T;
        dotGridStrokeWidth?: T;
        dotGridSizeRange?: T;
        dotGridOpacityRange?: T;
        dotGridShape?: T;
        simplexNoiseColors?:
          | T
          | {
              color?: T;
              id?: T;
            };
        simplexNoiseStepsPerColor?: T;
        simplexNoiseSoftness?: T;
        metaballsColors?:
          | T
          | {
              color?: T;
              id?: T;
            };
        metaballsColorBack?: T;
        metaballsCount?: T;
        metaballsSize?: T;
        wavesColorFront?: T;
        wavesColorBack?: T;
        wavesShape?: T;
        wavesAmplitude?: T;
        wavesFrequency?: T;
        wavesSpacing?: T;
        wavesProportion?: T;
        wavesSoftness?: T;
        perlinNoiseColorFront?: T;
        perlinNoiseColorBack?: T;
        perlinNoiseProportion?: T;
        perlinNoiseSoftness?: T;
        perlinNoiseOctaveCount?: T;
        perlinNoisePersistence?: T;
        perlinNoiseLacunarity?: T;
        voronoiColors?:
          | T
          | {
              color?: T;
              id?: T;
            };
        voronoiStepsPerColor?: T;
        voronoiColorGap?: T;
        voronoiColorGlow?: T;
        voronoiDistortion?: T;
        voronoiGap?: T;
        voronoiGlow?: T;
        warpColors?:
          | T
          | {
              color?: T;
              id?: T;
            };
        warpProportion?: T;
        warpSoftness?: T;
        warpShape?: T;
        warpShapeScale?: T;
        warpDistortion?: T;
        warpSwirl?: T;
        warpSwirlIterations?: T;
        godRaysColors?:
          | T
          | {
              color?: T;
              id?: T;
            };
        godRaysColorBack?: T;
        godRaysColorBloom?: T;
        godRaysBloom?: T;
        godRaysIntensity?: T;
        godRaysDensity?: T;
        godRaysSpotty?: T;
        godRaysMidSize?: T;
        godRaysMidIntensity?: T;
        spiralColorFront?: T;
        spiralColorBack?: T;
        spiralDensity?: T;
        spiralDistortion?: T;
        spiralStrokeWidth?: T;
        spiralStrokeTaper?: T;
        spiralStrokeCap?: T;
        spiralNoise?: T;
        spiralNoiseFrequency?: T;
        spiralSoftness?: T;
        swirlColors?:
          | T
          | {
              color?: T;
              id?: T;
            };
        swirlColorBack?: T;
        swirlBandCount?: T;
        swirlTwist?: T;
        swirlCenter?: T;
        swirlProportion?: T;
        swirlSoftness?: T;
        swirlNoise?: T;
        swirlNoiseFrequency?: T;
        ditheringColorFront?: T;
        ditheringColorBack?: T;
        ditheringShape?: T;
        ditheringType?: T;
        ditheringSize?: T;
        grainGradientColors?:
          | T
          | {
              color?: T;
              id?: T;
            };
        grainGradientColorBack?: T;
        grainGradientSoftness?: T;
        grainGradientIntensity?: T;
        grainGradientNoise?: T;
        grainGradientShape?: T;
        pulsingBorderColors?:
          | T
          | {
              color?: T;
              id?: T;
            };
        pulsingBorderColorBack?: T;
        pulsingBorderRoundness?: T;
        pulsingBorderThickness?: T;
        pulsingBorderSoftness?: T;
        pulsingBorderMargin?: T;
        pulsingBorderMarginLeft?: T;
        pulsingBorderMarginRight?: T;
        pulsingBorderMarginTop?: T;
        pulsingBorderMarginBottom?: T;
        pulsingBorderAspectRatio?: T;
        pulsingBorderIntensity?: T;
        pulsingBorderBloom?: T;
        pulsingBorderSpots?: T;
        pulsingBorderSpotSize?: T;
        pulsingBorderPulse?: T;
        pulsingBorderSmoke?: T;
        pulsingBorderSmokeSize?: T;
        colorPanelsColors?:
          | T
          | {
              color?: T;
              id?: T;
            };
        colorPanelsColorBack?: T;
        colorPanelsAngle1?: T;
        colorPanelsAngle2?: T;
        colorPanelsLength?: T;
        colorPanelsEdges?: T;
        colorPanelsBlur?: T;
        colorPanelsFadeIn?: T;
        colorPanelsFadeOut?: T;
        colorPanelsDensity?: T;
        colorPanelsGradient?: T;
        staticMeshGradientColors?:
          | T
          | {
              color?: T;
              id?: T;
            };
        staticMeshGradientPositions?: T;
        staticMeshGradientWaveX?: T;
        staticMeshGradientWaveXShift?: T;
        staticMeshGradientWaveY?: T;
        staticMeshGradientWaveYShift?: T;
        staticMeshGradientMixing?: T;
        staticMeshGradientGrainMixer?: T;
        staticMeshGradientGrainOverlay?: T;
        staticRadialGradientColors?:
          | T
          | {
              color?: T;
              id?: T;
            };
        staticRadialGradientColorBack?: T;
        staticRadialGradientRadius?: T;
        staticRadialGradientFocalDistance?: T;
        staticRadialGradientFocalAngle?: T;
        staticRadialGradientFalloff?: T;
        staticRadialGradientMixing?: T;
        staticRadialGradientDistortion?: T;
        staticRadialGradientDistortionShift?: T;
        staticRadialGradientDistortionFreq?: T;
        staticRadialGradientGrainMixer?: T;
        staticRadialGradientGrainOverlay?: T;
        paperTextureColorFront?: T;
        paperTextureColorBack?: T;
        paperTextureContrast?: T;
        paperTextureRoughness?: T;
        paperTextureFiber?: T;
        paperTextureFiberSize?: T;
        paperTextureCrumples?: T;
        paperTextureCrumpleSize?: T;
        paperTextureFolds?: T;
        paperTextureFoldCount?: T;
        paperTextureFade?: T;
        paperTextureDrops?: T;
        paperTextureSeed?: T;
        flutedGlassColorBack?: T;
        flutedGlassColorShadow?: T;
        flutedGlassColorHighlight?: T;
        flutedGlassShadows?: T;
        flutedGlassHighlights?: T;
        flutedGlassSize?: T;
        flutedGlassShape?: T;
        flutedGlassAngle?: T;
        flutedGlassDistortionShape?: T;
        flutedGlassDistortion?: T;
        flutedGlassShift?: T;
        flutedGlassStretch?: T;
        flutedGlassBlur?: T;
        flutedGlassEdges?: T;
        flutedGlassMargin?: T;
        flutedGlassGrainMixer?: T;
        flutedGlassGrainOverlay?: T;
        waterColorBack?: T;
        waterColorHighlight?: T;
        waterHighlights?: T;
        waterLayering?: T;
        waterEdges?: T;
        waterCaustic?: T;
        waterWaves?: T;
        waterSize?: T;
        imageDitheringColorFront?: T;
        imageDitheringColorBack?: T;
        imageDitheringColorHighlight?: T;
        imageDitheringType?: T;
        imageDitheringSize?: T;
        imageDitheringColorSteps?: T;
        imageDitheringOriginalColors?: T;
        imageDitheringInverted?: T;
        heatmapColors?:
          | T
          | {
              color?: T;
              id?: T;
            };
        heatmapColorBack?: T;
        heatmapContour?: T;
        heatmapAngle?: T;
        heatmapNoise?: T;
        heatmapInnerGlow?: T;
        heatmapOuterGlow?: T;
        liquidMetalColorBack?: T;
        liquidMetalColorTint?: T;
        liquidMetalRepetition?: T;
        liquidMetalSoftness?: T;
        liquidMetalShiftRed?: T;
        liquidMetalShiftBlue?: T;
        liquidMetalDistortion?: T;
        liquidMetalContour?: T;
        liquidMetalAngle?: T;
        liquidMetalShape?: T;
        halftoneDotsColorFront?: T;
        halftoneDotsColorBack?: T;
        halftoneDotsSize?: T;
        halftoneDotsGrid?: T;
        halftoneDotsRadius?: T;
        halftoneDotsContrast?: T;
        halftoneDotsOriginalColors?: T;
        halftoneDotsInverted?: T;
        halftoneDotsGrainMixer?: T;
        halftoneDotsGrainOverlay?: T;
        halftoneDotsGrainSize?: T;
        halftoneDotsType?: T;
        halftoneCmykColorBack?: T;
        halftoneCmykColorC?: T;
        halftoneCmykColorM?: T;
        halftoneCmykColorY?: T;
        halftoneCmykColorK?: T;
        halftoneCmykSize?: T;
        halftoneCmykMinDot?: T;
        halftoneCmykContrast?: T;
        halftoneCmykSoftness?: T;
        halftoneCmykGrainSize?: T;
        halftoneCmykGrainMixer?: T;
        halftoneCmykGrainOverlay?: T;
        halftoneCmykGridNoise?: T;
        halftoneCmykFloodC?: T;
        halftoneCmykFloodM?: T;
        halftoneCmykFloodY?: T;
        halftoneCmykFloodK?: T;
        halftoneCmykGainC?: T;
        halftoneCmykGainM?: T;
        halftoneCmykGainY?: T;
        halftoneCmykGainK?: T;
        halftoneCmykType?: T;
      };
  layout?:
    | T
    | {
        cta?: T | CallToActionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        archive?: T | ArchiveBlockSelect<T>;
        formBlock?: T | FormBlockSelect<T>;
        ourProcess?: T | OurProcessBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  richText?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        size?: T;
        richText?: T;
        enableLink?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock_select".
 */
export interface MediaBlockSelect<T extends boolean = true> {
  media?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock_select".
 */
export interface ArchiveBlockSelect<T extends boolean = true> {
  introContent?: T;
  populateBy?: T;
  relationTo?: T;
  categories?: T;
  limit?: T;
  selectedDocs?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock_select".
 */
export interface FormBlockSelect<T extends boolean = true> {
  form?: T;
  enableIntro?: T;
  introContent?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "OurProcessBlock_select".
 */
export interface OurProcessBlockSelect<T extends boolean = true> {
  heading?: T;
  subHeading?: T;
  steps?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  heroImage?: T;
  content?: T;
  relatedPosts?: T;
  categories?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  authors?: T;
  populatedAuthors?:
    | T
    | {
        id?: T;
        name?: T;
      };
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  featuredImage?: T;
  content?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  client?: T;
  date?: T;
  location?: T;
  projectStatus?: T;
  description?: T;
  categories?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  categories?:
    | T
    | {
        relationTo?: T;
        categoryID?: T;
        title?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null)
      | ({
          relationTo: 'projects';
          value: number | Project;
        } | null);
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock".
 */
export interface BannerBlock {
  style: 'info' | 'warning' | 'error' | 'success';
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock".
 */
export interface CodeBlock {
  language?: ('typescript' | 'javascript' | 'css') | null;
  code: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'code';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}